### PR TITLE
build(deps): update all dependencies to latest versions

### PR DESCRIPTION
**Pull request by rodmoreno**
This could close #1, #3, #5, #6, #7, #9, #10, #12 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Can you look into why CI is failing?

**Comment by rodmoreno** [comment]
In both cases looks like plugin did not start in time. Actually an error `ERR_AVVIO_PLUGIN_TIMEOUT` was emitted.

I think maybe in some cases `soap` module takes a long time to load the WSDL from dneonline.com

**Comment by mcollina** [comment]
I think it would be better to remove the dependency from an online service.

**Comment by rodmoreno** [comment]
Yeah! I refactored the code to include a local WSDL file so test can consume it from local instead online service

**Comment by rodmoreno** [comment]
I've submitted new commits to create a very basic mock service for testing.

dbfa4d6 is still failling because cannot connect to dneonline.com web service (https://github.com/fastify/fastify-soap-client/runs/2660054900#step:5:69)

**Review by climba03003 — COMMENTED** [review]
Can you add the `supported version of fastify` and `plugin name` to `fastify-plugin` option.
I think it is related to dependencies update.

https://github.com/fastify/fastify-soap-client/blob/master/index.js#L16

**Comment by rodmoreno** [comment]
Hey @climba03003 I've added metadata to `fastify-plugin`

**Review by climba03003 — APPROVED** [review]
LGTM.

**Pull request merged**
